// <auto-generated />
namespace LaheyHealth.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Changecompletedatetonull : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Changecompletedatetonull));
        
        string IMigrationMetadata.Id
        {
            get { return "201608111926153_Change complete date to null"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
