// <auto-generated />
namespace LaheyHealth.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Removingobligatorycompletedate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Removingobligatorycompletedate));
        
        string IMigrationMetadata.Id
        {
            get { return "201608111923154_Removing obligatory complete date"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
